### ISSUE TITLE
Removing mate-screen-shot and adding Kazam in the next release of MATE

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-utils#140]
A developer could add Kazam and remove mate-screenshot (in mate-utils) in the next release of MATE ?
https://github.com/mate-desktop/mate-utils/issues/129#issuecomment-203917582

**Comment by monsta** [comment]
Why would we want to add it? It has its own source code repo at https://launchpad.net/kazam.

**Comment by Petrouchka** [comment]
In Linux MINT MATE, Kazam is not installed, I must manually add it and I can't remove mate-screenshot. A lot of people are using MATE and want to use Kazam too, they are the same problem.

**Comment by raveit65** [comment]
> In Linux MINT MATE, Kazam is not installed, I must manually add it and I can't remove mate-screenshot. A lot of people are using MATE and want to use Kazam too, they have the same problem.

This is a packager issue in LinuxMint. In fedora mate-utils is split sub packages for every component. Here you can uninstall mate-screenshot and install what ever you want.
Btw. I don't think that Kazam have a conflict with mate-screenshot in LinuxMint. 

I'm closing this because Kazam is not available in every distro, and you did not give any general reason to do that.
