### ISSUE TITLE
The configure option --disable-silent-rules has no effect

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-utils#65]
Hi,

for mate-utils I discovered that the --disable-silent-rules configure option has no effect.

Any idea, how this may happen?

Mike

**Comment by monsta** [comment]
According to [this well-known doc](https://autotools.io/automake/silent.html), this line just adds backwards compatibility so automake < 1.11 would be happy. It's enough to write ```AM_SILENT_RULES([yes])``` these days.

As for the problem @sunweaver had, I suspect it was simply caused by using [shave](http://damien.lespiau.name/2009/02/shave-making-autotools-output-sane.html). It's a pre-silent rules hack that tries to do approximately the same - and of course ```--disable-silent-rules``` does not work with it. :smile:

I've removed shave in https://github.com/mate-desktop/mate-utils/pull/114.
